### ISSUE TITLE
Ужасное имя - это не лямбда

### ISSUE THREAD

**Issue by coursar** [Ronin52/McDonaldsWeb#5]
https://github.com/Ronin52/McDonaldsWeb/blob/b0c158aa3990ff83a3f98ee7f71b98aed9c9cb11/web-app/src/main/java/ru/rosbank/javaschool/web/servlet/FrontServlet.java#L80

**Comment by Ronin52** [comment]
Исправил, пушить 2 строчки не буду, закрою вручную
