### ISSUE TITLE
Консистентность - если Product положили в product, то Order нужно класть в order

### ISSUE THREAD

**Issue by coursar** [Ronin52/McDonaldsWeb#8]
https://github.com/Ronin52/McDonaldsWeb/blob/b0c158aa3990ff83a3f98ee7f71b98aed9c9cb11/web-app/src/main/java/ru/rosbank/javaschool/web/service/product/ProductService.java#L1

**Comment by Ronin52** [comment]
Раскидал по пакетам, везде, где это пропустил, пушить не буду, закрою вручную
